language: php  
php:  
  - 5.6
sudo: false  
before_script:  
  - mv .env.travis .env
  - chmod -R 777 storage
  - touch storage/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan serve >/dev/null 2>&1 &
script:  
  # Run tests
  - phpunit tests/
