language: php  
php:  
  - 5.6
sudo: false  
before_script:  
  # setup mysql (to test production) , and sqlite (for behat acceptance)
  # update composer,
  # then grab the packages,
  # chmod storage
  # migrate and seed db
  - mv .env.travis .env
  - chmod -R 777 storage
  - touch storage/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  #- npm install - if you want to use gulp/elixir
script:  
  # Run them tests, y'all
  - phpunit tests/
  #- vendor/bin/phpspec run -v
  #- vendor/bin/behat --config behat.yml